name: Build Test (Linux)
on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build miniupnpc
      run: |
        svn checkout https://github.com/miniupnp/miniupnp/trunk/miniupnpc
        cd miniupnpc
        make

    - name: make
      run: |
        mkdir obj
        make